[package]
name = "wgpu-cube"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30"
pollster = "0.3"
wgpu = "27.0"
glam = "0.28"
bytemuck = { version = "1.23", features = ["derive"] }
env_logger = "0.11"
log = "0.4"
